use expect_test::expect;

use super::*;

#[test]
fn no_directive_completion_in_layout_attribute() {
    check(
        r#"
//- /resources/views/layouts/foo.blade.php
Hello, World!

//- /index.blade.php
<x-foo-layout @$0
"#,
        expect![[r#"
"#]],
    );
}

#[test]
fn option_tag_attribute_directive() {
    cov_mark::check!(attr_completion);
    check(
        r#"
<select>
  <option @$0
</select>
"#,
        expect![[r#"
            @endif
            @endunless
            @endisset
            @endempty
            @endauth
            @endguest
            @endproduction
            @endenv
            @endsession
            @endcontext
            @endswitch
            @endfor
            @endforeach
            @endforelse
            @endwhile
            @endphp
            @if
            @unless
            @isset
            @empty
            @auth
            @guest
            @production
            @env
            @session
            @context
            @hassection
            @sectionmissing
            @switch
            @for
            @foreach
            @forelse
            @while
            @php
            @include
            @includeif
            @includewhen
            @includeunless
            @includefirst
            @includeisolated
            @class
            @style
            @disabled
            @selected"#]],
    );
}

#[test]
fn input_tag_attribute_directive() {
    check(
        r#"
<input @$0
"#,
        expect![[r#"
            @endif
            @endunless
            @endisset
            @endempty
            @endauth
            @endguest
            @endproduction
            @endenv
            @endsession
            @endcontext
            @endswitch
            @endfor
            @endforeach
            @endforelse
            @endwhile
            @endphp
            @if
            @unless
            @isset
            @empty
            @auth
            @guest
            @production
            @env
            @session
            @context
            @hassection
            @sectionmissing
            @switch
            @for
            @foreach
            @forelse
            @while
            @php
            @include
            @includeif
            @includewhen
            @includeunless
            @includefirst
            @includeisolated
            @class
            @style
            @disabled
            @readonly
            @required"#]],
    );
}

#[test]
fn no_directive_completion_in_component_attribute() {
    check(
        r#"
//- /resources/views/components/foo.blade.php
Hello, World!

//- /index.blade.php
<x-foo @$0
"#,
        expect![[r#"
"#]],
    );
}

#[test]
fn completes_after_at() {
    check(
        r#"
@$0
        "#,
        expect![[r#"
            @endif
            @endunless
            @endisset
            @endempty
            @endauth
            @endguest
            @endproduction
            @endenv
            @endsession
            @endcontext
            @endswitch
            @endfor
            @endforeach
            @endforelse
            @endwhile
            @endphp
            @if
            @unless
            @isset
            @empty
            @auth
            @guest
            @production
            @env
            @session
            @context
            @hassection
            @sectionmissing
            @switch
            @for
            @foreach
            @forelse
            @while
            @php
            @include
            @includeif
            @includewhen
            @includeunless
            @includefirst
            @includeisolated"#]],
    );
}

#[test]
fn no_complete_after_at_at() {
    cov_mark::check!(after_at_at);
    check(
        r#"
@@$0
"#,
        expect![""],
    );
}

#[test]
fn after_if() {
    check(
        r#"
@if(true)
@$0
        "#,
        expect![[r#"
            @endif
            @endunless
            @endisset
            @endempty
            @endauth
            @endguest
            @endproduction
            @endenv
            @endsession
            @endcontext
            @endswitch
            @endfor
            @endforeach
            @endforelse
            @endwhile
            @endphp
            @if
            @unless
            @isset
            @empty
            @auth
            @guest
            @production
            @env
            @session
            @context
            @hassection
            @sectionmissing
            @switch
            @for
            @foreach
            @forelse
            @while
            @php
            @include
            @includeif
            @includewhen
            @includeunless
            @includefirst
            @includeisolated
            @elseif
            @else"#]],
    );
}

#[test]
fn after_forelse() {
    check(
        r#"
@forelse($vals as $val)
@$0
"#,
        expect![[r#"
            @endif
            @endunless
            @endisset
            @endempty
            @endauth
            @endguest
            @endproduction
            @endenv
            @endsession
            @endcontext
            @endswitch
            @endfor
            @endforeach
            @endforelse
            @endwhile
            @endphp
            @if
            @unless
            @isset
            @empty
            @auth
            @guest
            @production
            @env
            @session
            @context
            @hassection
            @sectionmissing
            @switch
            @for
            @foreach
            @forelse
            @while
            @php
            @include
            @includeif
            @includewhen
            @includeunless
            @includefirst
            @includeisolated
            @break
            @continue"#]],
    );
}

#[test]
fn after_foreach() {
    check(
        r#"
@foreach($vals as $val)
@$0
"#,
        expect![[r#"
            @endif
            @endunless
            @endisset
            @endempty
            @endauth
            @endguest
            @endproduction
            @endenv
            @endsession
            @endcontext
            @endswitch
            @endfor
            @endforeach
            @endforelse
            @endwhile
            @endphp
            @if
            @unless
            @isset
            @empty
            @auth
            @guest
            @production
            @env
            @session
            @context
            @hassection
            @sectionmissing
            @switch
            @for
            @foreach
            @forelse
            @while
            @php
            @include
            @includeif
            @includewhen
            @includeunless
            @includefirst
            @includeisolated
            @break
            @continue"#]],
    );
}

#[test]
fn after_for() {
    check(
        r#"
@for($i = 0; $i < $val; $i++)
@$0
"#,
        expect![[r#"
            @endif
            @endunless
            @endisset
            @endempty
            @endauth
            @endguest
            @endproduction
            @endenv
            @endsession
            @endcontext
            @endswitch
            @endfor
            @endforeach
            @endforelse
            @endwhile
            @endphp
            @if
            @unless
            @isset
            @empty
            @auth
            @guest
            @production
            @env
            @session
            @context
            @hassection
            @sectionmissing
            @switch
            @for
            @foreach
            @forelse
            @while
            @php
            @include
            @includeif
            @includewhen
            @includeunless
            @includefirst
            @includeisolated
            @break
            @continue"#]],
    );
}

#[test]
fn after_while() {
    check(
        r#"
@while($val)
@$0
"#,
        expect![[r#"
            @endif
            @endunless
            @endisset
            @endempty
            @endauth
            @endguest
            @endproduction
            @endenv
            @endsession
            @endcontext
            @endswitch
            @endfor
            @endforeach
            @endforelse
            @endwhile
            @endphp
            @if
            @unless
            @isset
            @empty
            @auth
            @guest
            @production
            @env
            @session
            @context
            @hassection
            @sectionmissing
            @switch
            @for
            @foreach
            @forelse
            @while
            @php
            @include
            @includeif
            @includewhen
            @includeunless
            @includefirst
            @includeisolated
            @break
            @continue"#]],
    );
}

#[test]
fn after_switch() {
    check(
        r#"
@switch($val)
@$0
"#,
        expect![[r#"
            @endif
            @endunless
            @endisset
            @endempty
            @endauth
            @endguest
            @endproduction
            @endenv
            @endsession
            @endcontext
            @endswitch
            @endfor
            @endforeach
            @endforelse
            @endwhile
            @endphp
            @if
            @unless
            @isset
            @empty
            @auth
            @guest
            @production
            @env
            @session
            @context
            @hassection
            @sectionmissing
            @switch
            @for
            @foreach
            @forelse
            @while
            @php
            @include
            @includeif
            @includewhen
            @includeunless
            @includefirst
            @includeisolated
            @break
            @case
            @default"#]],
    );
}
