name: Release

on:
  push:
   branches:
     - main
#    tags:
#      - "*.*.*"

jobs:
  build-binary-and-extension:
    name: Build blase binary (${{ matrix.os }})
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            code_target: linux-x64
            artifact_name: blase
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code_target: win32-x64
            artifact_name: blase.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: editors/vscode/package-lock.json
      - name: Build binary executable and VS Code extension
        run: node dist.js ${{ matrix.target }} ${{ matrix.code_target }} ${{ matrix.artifact_name }} ${{ github.ref_name }}
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: blase-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-${{ matrix.code_target }}
          path: editors/vscode/blase-${{ matrix.code_target }}.vsix

  release:
    name: Upload to GitHub Release
    needs: build-binary-and-extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: blase-x86_64-unknown-linux-gnu
      - uses: actions/download-artifact@v4
        with:
          name: blase-x86_64-pc-windows-msvc
      - uses: actions/download-artifact@v4
        with:
          name: vsix-linux-x64
      - uses: actions/download-artifact@v4
        with:
          name: vsix-win32-x64
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            blase
            blase.exe
            blase-linux-x64.vsix
            blase-win32-x64.vsix
          generate_release_notes: true
